# Generated by Django 2.1.1 on 2018-10-30 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='carrito',
            fields=[
                ('idC', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('fecha', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='producto',
            fields=[
                ('idP', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('idU', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=50)),
                ('clave', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='venta',
            fields=[
                ('idV', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('idC', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplicacion.carrito')),
                ('idU', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplicacion.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='carrito',
            name='idP',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplicacion.producto'),
        ),
        migrations.AddField(
            model_name='carrito',
            name='idU',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplicacion.usuario'),
        ),
    ]
