# Generated by Django 2.1.1 on 2018-11-28 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='cantidad',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
